version: "3"
services: 
  node-app:
    build: .
    ports: 
      - "3000:3000"
    environment: 
      - PORT=3000
  mongo-db:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=vayam
      - MONGO_INITDB_ROOT_PASSWORD=rails
    volumes:
      - mongo-db:/data/db

volumes: 
  mongo-db: