version: "3"
services: 
  nginx:
    ports:
      - "80:80"
  node-app:
    build:
      context: .   #Used for the location
      args:
        NODE_ENV: production #Used to pass args
    environment: 
      - NODE_ENV=production
    command: node index.js 