version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
        - node-app    
  node-app:
    build: .
    image: vjhunt/node-docker-app
    environment: 
      - PORT=3000
    depends_on: 
      - mongo-db
  mongo-db:
    image: mongo
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=vayam
      - MONGO_INITDB_ROOT_PASSWORD=rails
    volumes:
      - mongo-db:/data/db
  redis-db:
    image: redis
volumes: 
  mongo-db:
  node-app: